/*
 * ThumbyNES — picker thumbnail / icon helpers.
 *
 * Two responsibilities:
 *
 *   1. Platform icon bitmaps. Seven 12×8 hand-painted icons (one per
 *      console, plus a star for the favourites tab) are stored as
 *      4 bpp index maps with a 4-entry per-icon palette in
 *      nes_tab_icons.inc — generated by tools/convert_tab_icons.py
 *      from the PNGs in tools/tab_icons/. Index 0 is transparent and
 *      index 1 is recoloured by the caller so the same bitmap drives
 *      the tab strip (tinted) and the placeholder thumbnails (white,
 *      nearest-neighbour upscaled to 24×16 / 48×32 inside 32×32 /
 *      64×64 panels). Total bitmap data: 7 × 56 = 392 bytes.
 *
 *   2. Screenshot sidecar I/O. Each ROM gets two raw RGB565 files
 *      written when the user presses MENU+A in-game:
 *
 *        /<basename>.scr32   32×32 ×2 bytes = 2 048 bytes
 *        /<basename>.scr64   64×64 ×2 bytes = 8 192 bytes
 *
 *      The 32×32 fits inline in the picker list view; the 64×64 is
 *      the hero in the default single-ROM view. We do nearest-style
 *      box averaging from the live 128×128 framebuffer (4×4 → 1 px
 *      for 32×32, 2×2 → 1 px for 64×64).
 */
#include "nes_thumb.h"
#include "nes_picker.h"   /* ROMS_DIR_SLASH — sidecar location */

#include <stdio.h>
#include <string.h>

#include "ff.h"

#define FB_W 128
#define FB_H 128

/* --- low-level fb helpers ------------------------------------------ */

static inline void put(uint16_t *fb, int x, int y, uint16_t c) {
    if ((unsigned)x < FB_W && (unsigned)y < FB_H) fb[y * FB_W + x] = c;
}

static void fill_rect(uint16_t *fb, int x, int y, int w, int h, uint16_t c) {
    for (int j = 0; j < h; j++) {
        int yy = y + j;
        if ((unsigned)yy >= FB_H) continue;
        for (int i = 0; i < w; i++) put(fb, x + i, yy, c);
    }
}

/* Draw a hollow rectangle outline. */
static void rect_outline(uint16_t *fb, int x, int y, int w, int h, uint16_t c) {
    for (int i = 0; i < w; i++) { put(fb, x + i, y, c); put(fb, x + i, y + h - 1, c); }
    for (int j = 0; j < h; j++) { put(fb, x, y + j, c); put(fb, x + w - 1, y + j, c); }
}

/* --- platform icon bitmaps ----------------------------------------- */

#define ICON_W 12
#define ICON_H 8

typedef struct {
    uint16_t pal[4];        /* literal RGB565 accent colours */
    uint8_t  bits[ICON_W * ICON_H / 2];   /* 4 bpp, two pixels per byte */
} tab_icon_t;

#include "nes_tab_icons.inc"

/* Map ICON_SYS_* / ROM_SYS_* → icons[] slot. ROM_SYS_NES..PCE happen
 * to be 0..5, matching the table; STAR is the only outlier. */
static int icon_slot(uint8_t which) {
    if (which == ICON_SYS_STAR) return 6;
    if (which < 6)              return (int)which;
    return -1;
}

/* Blit a 12×8 icon at (x,y), nearest-neighbour upscaled by `s`.
 * Index 0 = transparent, 1 = `tint`, 2..5 = ic->pal[index-2]. */
static void blit_icon(uint16_t *fb, int x, int y, int slot,
                      uint16_t tint, int s) {
    if (slot < 0) return;
    const tab_icon_t *ic = &icons[slot];
    for (int row = 0; row < ICON_H; row++) {
        for (int col = 0; col < ICON_W; col++) {
            int p = row * ICON_W + col;
            uint8_t byte = ic->bits[p >> 1];
            uint8_t pi = (p & 1) ? (byte >> 4) : (byte & 0x0F);
            if (pi == 0) continue;
            uint16_t c = (pi == 1) ? tint : ic->pal[pi - 2];
            if (s == 1) put(fb, x + col, y + row, c);
            else        fill_rect(fb, x + col * s, y + row * s, s, s, c);
        }
    }
}

void nes_thumb_icon(uint16_t *fb, int x, int y, uint8_t which, uint16_t tint) {
    blit_icon(fb, x, y, icon_slot(which), tint, 1);
}

void nes_thumb_placeholder(uint16_t *fb, int x, int y, int size, uint8_t system) {
    /* A coloured panel with the platform icon scaled to roughly half
     * the panel size. Reads as "no screenshot yet, system X". */
    static const uint16_t panel_for[] = {
        [ROM_SYS_NES] = 0x18C3, /* dim grey */
        [ROM_SYS_SMS] = 0x2104, /* dim red */
        [ROM_SYS_GG]  = 0x0204, /* dim teal */
        [ROM_SYS_GB]  = 0x1A40, /* dim olive — nods to the LCD green */
        [ROM_SYS_MD]  = 0x1082, /* dim slate blue — nods to the MD */
        [ROM_SYS_PCE] = 0x2001, /* dim maroon — nods to the PC Engine */
    };
    uint16_t panel = (system <= ROM_SYS_PCE) ? panel_for[system] : 0x18C3;
    fill_rect(fb, x, y, size, size, panel);
    rect_outline(fb, x, y, size, size, 0x4208);

    int s = size / 16;        /* icon scale: 32 → 2, 64 → 4 */
    if (s < 1) s = 1;
    int slot = icon_slot(system);
    if (slot < 0 || slot == 6) slot = 0;   /* unknown / star → fall back to NES */
    /* Centre the upscaled 12s × 8s icon inside the panel. */
    int ix = x + (size - ICON_W * s) / 2;
    int iy = y + (size - ICON_H * s) / 2;
    blit_icon(fb, ix, iy, slot, 0xFFFF, s);
}

/* --- screenshot sidecar I/O ---------------------------------------- */

static void scr_path(char *out, size_t outsz, const char *rom_name, int size) {
    char base[64];
    strncpy(base, rom_name, sizeof(base) - 1);
    base[sizeof(base) - 1] = 0;
    char *dot = strrchr(base, '.');
    if (dot) *dot = 0;
    snprintf(out, outsz, ROMS_DIR_SLASH "%s.scr%d", base, size);
}

bool nes_thumb_draw(uint16_t *fb, int x, int y, int size, const char *rom_name) {
    if (size != 32 && size != 64) return false;
    char path[NES_PICKER_PATH_MAX];
    scr_path(path, sizeof(path), rom_name, size);

    FIL f;
    if (f_open(&f, path, FA_READ) != FR_OK) return false;
    UINT expected = (UINT)(size * size * 2);
    if (f_size(&f) != expected) { f_close(&f); return false; }

    /* Read row-by-row directly into the framebuffer to avoid a
     * 8 KB scratch on the stack. The picker fb is 32 KB and lives
     * in BSS — we just write into the right rect. */
    for (int row = 0; row < size; row++) {
        int yy = y + row;
        if ((unsigned)yy >= FB_H) { f_close(&f); return true; }
        uint16_t *dst = fb + yy * FB_W + x;
        UINT br = 0;
        if (f_read(&f, dst, (UINT)(size * 2), &br) != FR_OK
            || br != (UINT)(size * 2)) {
            f_close(&f);
            return false;
        }
        /* Clip the right edge if x + size > FB_W. */
        if (x + size > FB_W) {
            int clip = (x + size) - FB_W;
            for (int i = 0; i < clip; i++) /* nothing — already past end */;
            (void)clip;
        }
    }
    f_close(&f);
    return true;
}

/* Box-average a w_src×w_src region of the source 128×128 framebuffer
 * down to a single output pixel. */
static uint16_t box_avg(const uint16_t *src, int sx, int sy, int n) {
    uint32_t r = 0, g = 0, b = 0;
    for (int j = 0; j < n; j++) {
        const uint16_t *row = src + (sy + j) * FB_W + sx;
        for (int i = 0; i < n; i++) {
            uint16_t p = row[i];
            r += (p >> 11) & 0x1F;
            g += (p >>  5) & 0x3F;
            b += (p      ) & 0x1F;
        }
    }
    int total = n * n;
    r /= total; g /= total; b /= total;
    return (uint16_t)((r << 11) | (g << 5) | b);
}

static int write_scr(const uint16_t *src, const char *rom_name, int size, int srcN) {
    /* Source is 128×128; downscale by srcN per output pixel. */
    char path[NES_PICKER_PATH_MAX];
    scr_path(path, sizeof(path), rom_name, size);

    FIL f;
    if (f_open(&f, path, FA_WRITE | FA_CREATE_ALWAYS) != FR_OK) return -1;

    /* Stream one row at a time so we never need a 8 KB scratch buffer. */
    uint16_t row[64];
    for (int oy = 0; oy < size; oy++) {
        for (int ox = 0; ox < size; ox++) {
            row[ox] = box_avg(src, ox * srcN, oy * srcN, srcN);
        }
        UINT bw = 0;
        if (f_write(&f, row, (UINT)(size * 2), &bw) != FR_OK
            || bw != (UINT)(size * 2)) {
            f_close(&f);
            return -2;
        }
    }
    f_close(&f);
    return 0;
}

int nes_thumb_save(const uint16_t *src, const char *rom_name) {
    /* 128 / 32 = 4 (4×4 average); 128 / 64 = 2 (2×2 average). */
    int rc = write_scr(src, rom_name, 32, 4);
    if (rc != 0) return rc;
    return write_scr(src, rom_name, 64, 2);
}
