#!/usr/bin/env python3
"""Encode the hand-painted 12x8 tab icons as a packed C table.

Each icon is stored as a 4-bit-per-pixel index map plus a 4-entry
per-icon palette of RGB565 accents:

    pal[0..3]  uint16_t  literal accent colours (RGB565)
    bits[48]   uint8_t   96 4-bit indices, two per byte
                          (low nibble = even pixel, high nibble = odd)

Reserved indices baked into the decoder:
    0 = transparent        (cell background shows through)
    1 = tint               (recoloured by caller — COL_TITLE/COL_DIM/0xFFFF)
    2..5 = pal[index - 2]  (literal RGB565)

PNG colour conventions (must match render_tab_icons.py):
    (255,   0, 255)  magenta  → transparent  → index 0
    (255, 166,   0)  orange   → tint         → index 1
    everything else            → literal      → index 2..5

Icon table order matches ROM_SYS_* in nes_picker.h so a system id
indexes directly. STAR (no ROM_SYS_ id) is appended at slot 6.
"""
from __future__ import annotations

import os
import sys
import textwrap

from PIL import Image

# Order MUST match ROM_SYS_* in nes_picker.h:
#   NES=0, SMS=1, GG=2, GB=3, MD=4, PCE=5, then STAR at 6.
ICONS = ["nes", "sms", "gg", "gb", "md", "pce", "star"]

W, H = 12, 8
TRANSP = (255, 0, 255)
TINT   = (255, 166, 0)
MAX_ACCENTS = 4   # 16 indices total, 2 reserved → 14 spare; we cap at 4 for compactness


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def encode(name: str, src_dir: str):
    img = Image.open(os.path.join(src_dir, f"{name}.png")).convert("RGB")
    if img.size != (W, H):
        sys.exit(f"{name}.png is {img.size}, expected {W}x{H}")

    pal: list[int] = []
    indices: list[int] = []
    for c in img.getdata():
        if c == TRANSP:
            indices.append(0)
            continue
        if c == TINT:
            indices.append(1)
            continue
        rgb565 = rgb_to_565(*c)
        if rgb565 in pal:
            indices.append(2 + pal.index(rgb565))
            continue
        if len(pal) >= MAX_ACCENTS:
            sys.exit(
                f"{name}: more than {MAX_ACCENTS} literal accent colours; "
                f"have {pal}, tried to add {c}"
            )
        pal.append(rgb565)
        indices.append(2 + len(pal) - 1)

    while len(pal) < MAX_ACCENTS:
        pal.append(0)

    packed = bytearray()
    for i in range(0, W * H, 2):
        a = indices[i]
        b = indices[i + 1]
        packed.append((b << 4) | a)

    return pal, packed


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(here, "tab_icons")
    out_path = os.path.normpath(os.path.join(here, "..", "device", "nes_tab_icons.inc"))

    lines: list[str] = []
    lines.append("/* Auto-generated by tools/convert_tab_icons.py — DO NOT EDIT. */")
    lines.append("/* 7 icons × 56 bytes = 392 bytes total. */")
    lines.append("static const tab_icon_t icons[7] = {")
    for name in ICONS:
        pal, bits = encode(name, src_dir)
        pal_s = ", ".join(f"0x{c:04x}" for c in pal)
        hex_bytes = [f"0x{b:02x}" for b in bits]
        # Wrap pixel bytes 12 per line (one row of the icon per line of source).
        bits_lines = [", ".join(hex_bytes[i:i + 12]) for i in range(0, len(hex_bytes), 12)]
        lines.append(f"    /* {name} */")
        lines.append(f"    {{ {{ {pal_s} }},")
        lines.append("      {")
        for bl in bits_lines:
            lines.append(f"        {bl},")
        # strip trailing comma on last bits line
        lines[-1] = lines[-1].rstrip(",")
        lines.append("      } },")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path} ({sum(len(l) for l in lines)} chars, "
          f"7 icons × 56 bytes = 392 bytes flash)")


if __name__ == "__main__":
    main()
