/*
 * ThumbyNES — generator for PicoDrive's YM2612 logarithmic lookup
 * tables (ym_tl_tab, ym_tl_tab2).
 *
 * Upstream PicoDrive computes these at first YM2612 init via
 * `init_tables()` in pico/sound/ym2612.c. That costs 212 992 + 6 656
 * bytes of heap for the life of the cart. On the RP2350 device build
 * we can't afford ~220 KB of runtime-allocated state when other
 * emulator cores need the RAM too. Precomputing at build time and
 * linking the data as `const` in flash moves the cost to flash (which
 * is plentiful) and lets the pointers in ym2612.c stay NULL at boot.
 *
 * Mirrors the math in vendor/picodrive/pico/sound/ym2612.c
 * init_tables() exactly. If that file's constants ever change, this
 * generator must be updated to match.
 *
 * Run from CMake; output is a single .c file with two arrays.
 */
#include <stdio.h>
#include <stdint.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define TL_RES_LEN  256
#define TL_TAB_LEN  (13*TL_RES_LEN*256/8)   /* 106 496 entries, 213 KB u16 */
#define ENV_STEP    (128.0/64.0)             /* matches ym2612.c */
#define SIN_LEN     1024                     /* matches ym2612.c */

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s out.c\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror(argv[1]); return 1; }

    static uint16_t sin_tab[256];
    static uint16_t tl_tab2[13 * TL_RES_LEN];
    static uint16_t tl_tab [TL_TAB_LEN];

    /* Mirror of init_tables() from ym2612.c ---------------------- */

    for (int i = 0; i < 256; i++) {
        /* non-standard sinus */
        double m = sin(((i * 2) + 1) * M_PI / SIN_LEN);
        double o;
        if (m > 0.0) o = 8 * log(1.0 / m) / log(2);
        else         o = 8 * log(-1.0 / m) / log(2);
        o = o / (ENV_STEP / 4);
        int n = (int)(2.0 * o);
        if (n & 1) n = (n >> 1) + 1;
        else       n = n >> 1;
        sin_tab[i] = (uint16_t)n;
    }

    for (int x = 0; x < TL_RES_LEN; x++) {
        double m = (1 << 16) / pow(2, (x + 1) * (ENV_STEP / 4.0) / 8.0);
        m = floor(m);
        int n = (int)m;
        n >>= 4;
        if (n & 1) n = (n >> 1) + 1;
        else       n = n >> 1;
        n <<= 2;
        tl_tab2[x] = (uint16_t)n;
        for (int i = 1; i < 13; i++) {
            tl_tab2[x + i * TL_RES_LEN] = (uint16_t)(n >> i);
        }
    }

    for (int x = 0; x < 256; x++) {
        int sn = sin_tab[x];
        for (int y = 0; y < 2 * 13 * TL_RES_LEN / 8; y += 2) {
            int p = (y << 2) + sn;
            if (p >= 13 * TL_RES_LEN) tl_tab[(y << 7) | x] = 0;
            else                      tl_tab[(y << 7) | x] = tl_tab2[p];
        }
    }

    /* ---- emit as const data ------------------------------------ */

    fprintf(f, "/* Auto-generated by tools/gen_md_ym2612_tab.c. Do not edit. */\n");
    fprintf(f, "#include <stdint.h>\n\n");

    fprintf(f, "const uint16_t md_ym_tl_tab_data[%d] = {\n", TL_TAB_LEN);
    for (int i = 0; i < TL_TAB_LEN; i++) {
        fprintf(f, "0x%04x,", tl_tab[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n\n");

    fprintf(f, "const uint16_t md_ym_tl_tab2_data[13 * %d] = {\n", TL_RES_LEN);
    for (int i = 0; i < 13 * TL_RES_LEN; i++) {
        fprintf(f, "0x%04x,", tl_tab2[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n");

    fclose(f);
    return 0;
}
