/*
 * ThumbyNES — generator for PicoDrive's FAME 68K JumpTable.
 *
 * FAME runtime-builds a 65536-entry jump table mapping every possible
 * 16-bit 68K opcode to the OP_0xXXXX function that handles it. That's
 * 256 KB of BSS, half of the RP2350's SRAM budget. Precompute the
 * mapping at build time and emit it as a `const` array of function
 * pointers — the linker resolves each OP_0xXXXX symbol address, the
 * table lives in flash, zero SRAM cost.
 *
 * Strategy: include the same init_jump_table body FAME uses, but with
 * CAST_OP redefined to capture the opcode NUMBER (u16) that each
 * JumpTable entry should dispatch to. Then emit designated
 * initialisers `[idx] = OP_0xYYYY,` that famec.c #includes. When the
 * device build picks up this file, GCC resolves each OP_0xYYYY into
 * the function's link-time address.
 */
#include <stdio.h>
#include <stdint.h>

typedef uint16_t u16;
typedef uint32_t u32;

/* Capture the opcode ID each JumpTable entry was set to. */
static u32 JumpTable[0x10000];

/* In the original famec.c, CAST_OP yields an opcode_func pointer. For
 * the generator, it yields the raw opcode number so we can print it. */
#define CAST_OP(N_OP) (N_OP)

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s out.c\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror(argv[1]); return 1; }

    u32 i, j;
    (void)j;

    /* Mirror of the init body in famec.c. Using the same .inc file
     * keeps the two variants in lockstep. */
    #include "../vendor/picodrive/cpu/fame/famec_jumptable_init.inc"

    fprintf(f, "/* Auto-generated by tools/gen_md_fame_jumptable.c. Do not edit. */\n\n");
    for (int k = 0; k < 0x10000; k++) {
        fprintf(f, "[0x%04X] = OP_0x%04X,", k, JumpTable[k]);
        if ((k & 7) == 7) fputc('\n', f);
    }

    fclose(f);
    return 0;
}
