/*
 * ThumbyNES — generator for PicoDrive's cz80 SZHVC flag tables.
 *
 * cz80's Cz80_Init() runtime-builds SZHVC_add[2*256*256] (128 KB) and
 * SZHVC_sub[2*256*256] (128 KB) — Z80 flag tables for SBC/ADC/SUB/ADD.
 * That's 256 KB of BSS, half of the RP2350's SRAM, for tables that are
 * fully deterministic from a simple loop.
 *
 * Precompute at build time and link as const data in flash — saves
 * 256 KB of SRAM during MD sessions. Mirrors the loop at
 * vendor/picodrive/cpu/cz80/cz80.c lines ~138..185 exactly.
 */
#include <stdio.h>
#include <stdint.h>

/* Z80 flag bits — copied from vendor/picodrive/cpu/cz80/cz80.h. */
#define CF  0x01
#define NF  0x02
#define PF  0x04
#define VF  PF
#define XF  0x08
#define HF  0x10
#define YF  0x20
#define ZF  0x40
#define SF  0x80

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s out.c\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror(argv[1]); return 1; }

    static uint8_t add[2 * 256 * 256];
    static uint8_t sub[2 * 256 * 256];
    uint8_t *padd = &add[      0];
    uint8_t *padc = &add[256 * 256];
    uint8_t *psub = &sub[      0];
    uint8_t *psbc = &sub[256 * 256];

    for (int oldval = 0; oldval < 256; oldval++) {
        for (int newval = 0; newval < 256; newval++) {
            int val;

            val = newval - oldval;
            *padd  = (newval) ? ((newval & 0x80) ? SF : 0) : ZF;
            *padd |= (newval & (YF | XF));
            if ((newval & 0x0f) < (oldval & 0x0f)) *padd |= HF;
            if ( newval         <  oldval        ) *padd |= CF;
            if ((val ^ oldval ^ 0x80) & (val ^ newval) & 0x80) *padd |= VF;
            padd++;

            val = newval - oldval - 1;
            *padc  = (newval) ? ((newval & 0x80) ? SF : 0) : ZF;
            *padc |= (newval & (YF | XF));
            if ((newval & 0x0f) <= (oldval & 0x0f)) *padc |= HF;
            if ( newval         <= oldval        ) *padc |= CF;
            if ((val ^ oldval ^ 0x80) & (val ^ newval) & 0x80) *padc |= VF;
            padc++;

            val = oldval - newval;
            *psub  = NF | ((newval) ? ((newval & 0x80) ? SF : 0) : ZF);
            *psub |= (newval & (YF | XF));
            if ((newval & 0x0f) > (oldval & 0x0f)) *psub |= HF;
            if ( newval         >  oldval        ) *psub |= CF;
            if ((val ^ oldval) & (oldval ^ newval) & 0x80) *psub |= VF;
            psub++;

            val = oldval - newval - 1;
            *psbc  = NF | ((newval) ? ((newval & 0x80) ? SF : 0) : ZF);
            *psbc |= (newval & (YF | XF));
            if ((newval & 0x0f) >= (oldval & 0x0f)) *psbc |= HF;
            if ( newval         >= oldval        ) *psbc |= CF;
            if ((val ^ oldval) & (oldval ^ newval) & 0x80) *psbc |= VF;
            psbc++;
        }
    }

    fprintf(f, "/* Auto-generated by tools/gen_md_cz80_szhvc.c. Do not edit. */\n");
    fprintf(f, "#include <stdint.h>\n\n");

    fprintf(f, "const uint8_t md_cz80_szhvc_add_data[2*256*256] = {\n");
    for (int i = 0; i < 2 * 256 * 256; i++) {
        fprintf(f, "0x%02x,", add[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n\n");

    fprintf(f, "const uint8_t md_cz80_szhvc_sub_data[2*256*256] = {\n");
    for (int i = 0; i < 2 * 256 * 256; i++) {
        fprintf(f, "0x%02x,", sub[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n");

    fclose(f);
    return 0;
}
