/*
 * ThumbyNES — generator for PicoDrive's YM2612 logarithmic lookup
 * tables (ym_tl_tab, ym_tl_tab2).
 *
 * Upstream PicoDrive computes these at first YM2612 init via
 * `init_tables()` in pico/sound/ym2612.c. That costs 212 992 + 6 656
 * bytes of heap for the life of the cart. On the RP2350 device build
 * we can't afford ~220 KB of runtime-allocated state when other
 * emulator cores need the RAM too. Precomputing at build time and
 * linking the data as `const` in flash moves the cost to flash (which
 * is plentiful) and lets the pointers in ym2612.c stay NULL at boot.
 *
 * Mirrors the math in vendor/picodrive/pico/sound/ym2612.c
 * init_tables() exactly. If that file's constants ever change, this
 * generator must be updated to match.
 *
 * Run from CMake; output is a single .c file with two arrays.
 */
#include <stdio.h>
#include <stdint.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define TL_RES_LEN  256
#define TL_TAB_LEN  (13*TL_RES_LEN*256/8)   /* 106 496 entries, 213 KB u16 */
#define ENV_STEP    (128.0/64.0)             /* matches ym2612.c */
#define SIN_LEN     1024                     /* matches ym2612.c */

/* Copied verbatim from vendor/picodrive/pico/sound/ym2612.c lines
 * 451..522. If you update one, update the other. */
static const uint8_t lfo_pm_output[7*8][8] = {
/* FNUM BIT 4 */
{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},
{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,1,1,1,1},
/* FNUM BIT 5 */
{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},
{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,1,1,1,1},{0,0,1,1,2,2,2,3},
/* FNUM BIT 6 */
{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},
{0,0,0,0,0,0,0,1},{0,0,0,0,1,1,1,1},{0,0,1,1,2,2,2,3},{0,0,2,3,4,4,5,6},
/* FNUM BIT 7 */
{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},{0,0,0,0,0,0,1,1},{0,0,0,0,1,1,1,1},
{0,0,0,1,1,1,1,2},{0,0,1,1,2,2,2,3},{0,0,2,3,4,4,5,6},{0,0,4,6,8,8,0xa,0xc},
/* FNUM BIT 8 */
{0,0,0,0,0,0,0,0},{0,0,0,0,1,1,1,1},{0,0,0,1,1,1,2,2},{0,0,1,1,2,2,3,3},
{0,0,1,2,2,2,3,4},{0,0,2,3,4,4,5,6},{0,0,4,6,8,8,0xa,0xc},{0,0,8,0xc,0x10,0x10,0x14,0x18},
/* FNUM BIT 9 */
{0,0,0,0,0,0,0,0},{0,0,0,0,2,2,2,2},{0,0,0,2,2,2,4,4},{0,0,2,2,4,4,6,6},
{0,0,2,4,4,4,6,8},{0,0,4,6,8,8,0xa,0xc},{0,0,8,0xc,0x10,0x10,0x14,0x18},{0,0,0x10,0x18,0x20,0x20,0x28,0x30},
/* FNUM BIT 10 */
{0,0,0,0,0,0,0,0},{0,0,0,0,4,4,4,4},{0,0,0,4,4,4,8,8},{0,0,4,4,8,8,0xc,0xc},
{0,0,4,8,8,8,0xc,0x10},{0,0,8,0xc,0x10,0x10,0x14,0x18},{0,0,0x10,0x18,0x20,0x20,0x28,0x30},{0,0,0x20,0x30,0x40,0x40,0x50,0x60},
};

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s out.c\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror(argv[1]); return 1; }

    static uint16_t sin_tab[256];
    static uint16_t tl_tab2[13 * TL_RES_LEN];
    static uint16_t tl_tab [TL_TAB_LEN];

    /* Mirror of init_tables() from ym2612.c ---------------------- */

    for (int i = 0; i < 256; i++) {
        /* non-standard sinus */
        double m = sin(((i * 2) + 1) * M_PI / SIN_LEN);
        double o;
        if (m > 0.0) o = 8 * log(1.0 / m) / log(2);
        else         o = 8 * log(-1.0 / m) / log(2);
        o = o / (ENV_STEP / 4);
        int n = (int)(2.0 * o);
        if (n & 1) n = (n >> 1) + 1;
        else       n = n >> 1;
        sin_tab[i] = (uint16_t)n;
    }

    for (int x = 0; x < TL_RES_LEN; x++) {
        double m = (1 << 16) / pow(2, (x + 1) * (ENV_STEP / 4.0) / 8.0);
        m = floor(m);
        int n = (int)m;
        n >>= 4;
        if (n & 1) n = (n >> 1) + 1;
        else       n = n >> 1;
        n <<= 2;
        tl_tab2[x] = (uint16_t)n;
        for (int i = 1; i < 13; i++) {
            tl_tab2[x + i * TL_RES_LEN] = (uint16_t)(n >> i);
        }
    }

    for (int x = 0; x < 256; x++) {
        int sn = sin_tab[x];
        for (int y = 0; y < 2 * 13 * TL_RES_LEN / 8; y += 2) {
            int p = (y << 2) + sn;
            if (p >= 13 * TL_RES_LEN) tl_tab[(y << 7) | x] = 0;
            else                      tl_tab[(y << 7) | x] = tl_tab2[p];
        }
    }

    /* ---- emit as const data ------------------------------------ */

    fprintf(f, "/* Auto-generated by tools/gen_md_ym2612_tab.c. Do not edit. */\n");
    fprintf(f, "#include <stdint.h>\n\n");

    fprintf(f, "const uint16_t md_ym_tl_tab_data[%d] = {\n", TL_TAB_LEN);
    for (int i = 0; i < TL_TAB_LEN; i++) {
        fprintf(f, "0x%04x,", tl_tab[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n\n");

    fprintf(f, "const uint16_t md_ym_tl_tab2_data[13 * %d] = {\n", TL_RES_LEN);
    for (int i = 0; i < 13 * TL_RES_LEN; i++) {
        fprintf(f, "0x%04x,", tl_tab2[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n\n");

    /* ---- lfo_pm_table: 128 KB of INT32 LFO phase modulation values.
     * Computed from lfo_pm_output via the exact loop in ym2612.c
     * init_tables (lines ~1569..1599). Fully deterministic, doesn't
     * depend on sample rate. */
    static int32_t lfo_pm[128 * 8 * 32];
    for (int i = 0; i < 8; i++) {                /* 8 PM depths */
        for (int fnum = 0; fnum < 128; fnum++) {  /* 7 bits of F-NUMBER */
            uint8_t offset_depth = i;
            for (int step = 0; step < 8; step++) {
                uint8_t value = 0;
                for (int bit_tmp = 0; bit_tmp < 7; bit_tmp++) {
                    if (fnum & (1 << bit_tmp)) {
                        int offset_fnum_bit = bit_tmp * 8;
                        value += lfo_pm_output[offset_fnum_bit + offset_depth][step];
                    }
                }
                lfo_pm[(fnum*32*8) + (i*32) + step    + 0 ] =  value;
                lfo_pm[(fnum*32*8) + (i*32) +(step^7) + 8 ] =  value;
                lfo_pm[(fnum*32*8) + (i*32) + step    + 16] = -value;
                lfo_pm[(fnum*32*8) + (i*32) +(step^7) + 24] = -value;
            }
        }
    }
    fprintf(f, "const int32_t md_ym_lfo_pm_data[128*8*32] = {\n");
    for (int i = 0; i < 128*8*32; i++) {
        fprintf(f, "%d,", lfo_pm[i]);
        if ((i & 15) == 15) fputc('\n', f);
    }
    fprintf(f, "};\n");

    fclose(f);
    return 0;
}
